/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author juanc
 */
public class CivitasView extends javax.swing.JFrame {

    private CivitasJuego juego;
    private JugadorPanel jugadorPanel;
    private GestionarDialog gestionarD;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        jugadorPanel = new JugadorPanel();
        gestionarD = new GestionarDialog( this );
//        contenedorGestionar.add( gestionarD );
        contenedorVistaJugador.add (jugadorPanel);
        repaint();
        revalidate();
    }
    
    public void gestionar(){
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
    
    public int getGestion() {
        return gestionarD.getGestion();
    }

    public int getPropiedad() {
        return gestionarD.getPropiedad();
    }
    
    public void mostrarSiguienteOperacion( String sigOp ){
        TextSiguienteOperacion.setText(sigOp);
        actualizarVista();
    }
    
    public void mostrarEventos(){
        DiarioDialog diarioD = new DiarioDialog(this); //crea la ventana del diario
        diarioD.repaint();
        diarioD.revalidate();
    }
    
    public Respuestas comprar(){       
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?","Compra", JOptionPane.YES_NO_OPTION);
        if( opcion == 0 ){ //SI
            return Respuestas.SI;
        }else        //No
            return Respuestas.NO;
    }
    
    public SalidasCarcel salirCarcel(){
        String[] opciones= { "Pagando", "Tirando" };
        
        int respuesta= JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?",
            "Salir de la cárcel", JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0] );
        
        return SalidasCarcel.values()[respuesta];
    }
    
    public void actualizarVista(){
        etiqRanking.setVisible(false);
        TextRanking.setVisible(false);
        jugadorPanel.setJugador( juego.getJugadorActual() );
        jugadorPanel.setVisible(true);
//        contenedorVistaJugador.setVisible(true);
        ContenedorCasillaActual.setText(juego.getCasillaActual().toString());
//        TextCasillaActual.setText(juego.getCasillaActual().toString());
        
        if( juego.finalDelJuego() ){
            String ranking = "";
            for( Jugador jugador : juego.ranking() )
                ranking += jugador.getNombre() + " con saldo " + jugador.getSaldo() + '\n';
            
            TextRanking.setText( ranking );
            etiqRanking.setVisible(true);
            TextRanking.setVisible(true);
            repaint();
            revalidate();
        }else
            repaint();
        
    }
    
    public void setCivitasJuego( CivitasJuego game ){
        juego = game;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_Titulo = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        etiqSigOp = new javax.swing.JLabel();
        TextSiguienteOperacion = new javax.swing.JTextField();
        etiqRanking = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ContenedorCasillaActual = new javax.swing.JTextArea();
        etiqCasillaActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextRanking = new javax.swing.JTextArea();
        etiqCasillaActual1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Civitas El Juego");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etiq_Titulo.setBackground(new java.awt.Color(255, 153, 153));
        etiq_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiq_Titulo.setText("Civitas El Juego");
        etiq_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 153, 153), null, null));
        etiq_Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        contenedorVistaJugador.setBackground(new java.awt.Color(204, 255, 204));
        contenedorVistaJugador.setEnabled(false);
        contenedorVistaJugador.setFocusCycleRoot(true);

        etiqSigOp.setBackground(new java.awt.Color(255, 255, 255));
        etiqSigOp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqSigOp.setText("Siguiente Operacion");

        TextSiguienteOperacion.setBackground(new java.awt.Color(153, 153, 255));
        TextSiguienteOperacion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextSiguienteOperacion.setEnabled(false);

        etiqRanking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqRanking.setText("Ranking");

        ContenedorCasillaActual.setBackground(new java.awt.Color(255, 255, 204));
        ContenedorCasillaActual.setColumns(20);
        ContenedorCasillaActual.setRows(5);
        ContenedorCasillaActual.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ContenedorCasillaActual.setEnabled(false);
        jScrollPane3.setViewportView(ContenedorCasillaActual);

        etiqCasillaActual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqCasillaActual.setText("Jugador");

        jScrollPane1.setEnabled(false);

        TextRanking.setBackground(new java.awt.Color(153, 255, 204));
        TextRanking.setColumns(20);
        TextRanking.setRows(5);
        TextRanking.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextRanking.setEnabled(false);
        jScrollPane1.setViewportView(TextRanking);

        etiqCasillaActual1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiqCasillaActual1.setText("Casilla Actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(etiqCasillaActual1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(etiqSigOp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqCasillaActual)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(etiqRanking)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(etiq_Titulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(etiq_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqCasillaActual)
                    .addComponent(etiqSigOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqCasillaActual1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiqRanking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ContenedorCasillaActual;
    private javax.swing.JTextArea TextRanking;
    private javax.swing.JTextField TextSiguienteOperacion;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JLabel etiqCasillaActual;
    private javax.swing.JLabel etiqCasillaActual1;
    private javax.swing.JLabel etiqRanking;
    private javax.swing.JLabel etiqSigOp;
    private javax.swing.JLabel etiq_Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
