/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.*;
import java.util.ArrayList;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author juanc
 */
public class JugadorPanel extends javax.swing.JPanel {
    
    Jugador jugador;
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
//        propiedades = new PropiedadPanel();
    }
    
    public void setJugador( Jugador gamer ){
        jugador = gamer;
        TextSaldo.setText( Float.toString(jugador.getSaldo()) );
        TextNombre.setText( jugador.getNombre() );
        TextEncarcelado.setText( jugador.encarcelado ? "Si" : "NO" );
        TextEspeculador.setText( ( jugador instanceof JugadorEspeculador)? "Si" : "NO"  );
        TextIndiceCasilla.setText( Integer.toString( jugador.getNumCasillaActual() ) );
        rellenaPropiedades( jugador.getPropiedades() );
//        propiedades.add(propiedades);
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<TituloPropiedad> lista) {
        // Se elimina la información antigua
        propiedades.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y        añadirlas al panel
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
//        propiedades.setVisible(true);

        // Se fuerza la actualización visual del panel propiedades y del panel del jugador     
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_saldo = new javax.swing.JLabel();
        etiq_encarcelado = new javax.swing.JLabel();
        etiq_Especulador = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        TextSaldo = new javax.swing.JTextField();
        TextEncarcelado = new javax.swing.JTextField();
        TextEspeculador = new javax.swing.JTextField();
        etiq_indice = new javax.swing.JLabel();
        TextIndiceCasilla = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();

        etiq_saldo.setText("Saldo");

        etiq_encarcelado.setText("Encarcelado");

        etiq_Especulador.setText("Especulador");

        TextNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextNombre.setText("jTextField1");

        TextSaldo.setText("jTextField2");

        TextEncarcelado.setText("jTextField3");

        TextEspeculador.setText("jTextField4");

        etiq_indice.setText("Indice Casilla");

        TextIndiceCasilla.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_saldo)
                            .addComponent(etiq_encarcelado))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_Especulador)
                                .addGap(22, 22, 22)
                                .addComponent(TextEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_indice)
                                .addGap(18, 18, 18)
                                .addComponent(TextIndiceCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiq_Especulador)
                    .addComponent(etiq_saldo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_indice)
                    .addComponent(TextEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextIndiceCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiq_encarcelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextEncarcelado;
    private javax.swing.JTextField TextEspeculador;
    private javax.swing.JTextField TextIndiceCasilla;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextSaldo;
    private javax.swing.JLabel etiq_Especulador;
    private javax.swing.JLabel etiq_encarcelado;
    private javax.swing.JLabel etiq_indice;
    private javax.swing.JLabel etiq_saldo;
    private javax.swing.JPanel propiedades;
    // End of variables declaration//GEN-END:variables
}
